import React, { useState, useEffect } from "react";
import {
  Box,
  Card,
  CardContent,
  Chip,
  CircularProgress,
  Divider,
  Paper,
  Typography,
  Alert,
} from "@mui/material";
import HistoryIcon from "@mui/icons-material/History";
import SmartToyIcon from "@mui/icons-material/SmartToy";
import { researchService } from "../services/api";
import { useAuth } from "../context/AuthContext";

function QueryHistory() {
  const { userRole } = useAuth();
  const isAuditor = userRole === "Reviewer" || userRole === "Administrator";

  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    fetchHistory();
  }, []);

  const fetchHistory = async () => {
    try {
      setLoading(true);
      setError("");
      const res = await researchService.getHistory();
      if (res.success && Array.isArray(res.data)) {
        setHistory(res.data);
      }
    } catch (err) {
      setError(err.message || "Failed to load query history.");
    } finally {
      setLoading(false);
    }
  };

  const formatDate = (dateStr) => {
    if (!dateStr) return "";
    return new Date(dateStr).toLocaleString("en-IN", {
      dateStyle: "medium",
      timeStyle: "short",
    });
  };

  return (
    <Box>
      <Box sx={{ mb: 3, display: "flex", alignItems: "center", gap: 1 }}>
        <HistoryIcon color="primary" sx={{ fontSize: 32 }} />
        <Box>
          <Typography variant="h4" fontWeight="bold">
            {isAuditor ? "System AI Usage & Query History" : "My Research Query History"}
          </Typography>
          <Typography color="text.secondary">
            {isAuditor
              ? "Reviewing AI usage and query activity across the knowledge platform."
              : "View your past questions and answers generated by the AI research agent."}
          </Typography>
        </Box>
      </Box>

      {error && <Alert severity="error" sx={{ mb: 3 }}>{error}</Alert>}

      {loading ? (
        <Box sx={{ display: "flex", justifyContent: "center", py: 6 }}>
          <CircularProgress />
        </Box>
      ) : history.length === 0 ? (
        <Card>
          <CardContent sx={{ textAlign: "center", py: 5 }}>
            <HistoryIcon sx={{ fontSize: 50, color: "text.secondary", mb: 1 }} />
            <Typography variant="h6" fontWeight="bold">
              No Query History Yet
            </Typography>
            <Typography color="text.secondary">
              Go to the Research Assistant page to ask questions using the knowledge base.
            </Typography>
          </CardContent>
        </Card>
      ) : (
        <Box sx={{ display: "flex", flexDirection: "column", gap: 2 }}>
          {history.map((item) => (
            <Card key={item.id} variant="outlined">
              <CardContent>
                <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", mb: 1.5, gap: 1, flexWrap: "wrap" }}>
                  <Box>
                    <Typography variant="h6" fontWeight="bold" color="primary">
                      Q: {item.questionText}
                    </Typography>
                    {isAuditor && (item.userFullName || item.userEmail) && (
                      <Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 0.5 }}>
                        Asked by: <strong>{item.userFullName || item.userEmail}</strong> ({item.userEmail})
                      </Typography>
                    )}
                  </Box>
                  <Chip label={formatDate(item.createdAt)} size="small" variant="outlined" />
                </Box>

                <Divider sx={{ my: 1.5 }} />

                <Box sx={{ display: "flex", gap: 1, mb: 1 }}>
                  <SmartToyIcon color="secondary" fontSize="small" sx={{ mt: 0.3 }} />
                  <Typography variant="body1" sx={{ whiteSpace: "pre-wrap", lineHeight: 1.7 }}>
                    {item.answerText}
                  </Typography>
                </Box>

                {item.sourceChunkIds && (
                  <Box sx={{ mt: 2, display: "flex", gap: 1, alignItems: "center" }}>
                    <Typography variant="caption" color="text.secondary">
                      Cited Vector Chunks:
                    </Typography>
                    <Chip label={`Chunks #${item.sourceChunkIds}`} size="small" color="default" />
                  </Box>
                )}
              </CardContent>
            </Card>
          ))}
        </Box>
      )}
    </Box>
  );
}

export default QueryHistory;
